### ISSUE TITLE
error: PLAIN authentication is not an option

### ISSUE THREAD

**Issue by enzo-yang** [xmppo/go-xmpp#23]
my code is:

```
package main

import (
    "fmt"
    xmpp "github.com/mattn/go-xmpp"
)

const (
    server   = "talk.google.com:5222"
    username = "myusername"
    password = "mypassword"
)

func main() {
    fmt.Println("hello")
    talk, err := xmpp.NewClientNoTLS(server, username, password, true)
    fmt.Println("error: " + err.Error())
    talk.Send(xmpp.Chat{Remote: "xxx@gmail.com", Type: "chat", Text: "hello yangxiao"})
}
```

and get the result

```
<stream:stream from="gmail.com" id="0C8386F233123077" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client"><stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"><required/></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:
xmpp-sasl"><mechanism>X-OAUTH2</mechanism><mechanism>X-GOOGLE-TOKEN</mechanism></mechanisms></stream:features>
error: PLAIN authentication is not an option: [X-OAUTH2 X-GOOGLE-TOKEN]
panic: runtime error: invalid memory address or nil pointer dereference

[signal 0xb code=0x1 addr=0x0 pc=0x39764]

goroutine 1 [running]:
github.com/mattn/go-xmpp.(*Client).Send(0x0, 0x253b10, 0x15, 0x231120, 0x4, ...)
        /Users/EnzoYang/src/go_path/src/github.com/mattn/go-xmpp/xmpp.go:398 +0x1b4 
main.main()
        /Users/EnzoYang/Work/Vagrant/pypy/workspace/GO/src/nagi-notify/gtalk.go:19 +0x238

goroutine 2 [syscall]:

```

my os is mac os x 10.9, my go version is 1.1.2

**Comment by skiz** [comment]
PLAIN is not supported when not using TLS(SSL).  When connecting to port 443, you will receive this mechanism list, which includes plain, as the connection is encrypted.  I don't believe that Google supports PLAIN on unencrypted connections (and you are using NoTLS connection).

'''
<stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>X-OAUTH2</mechanism><mechanism>X-GOOGLE-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms></stream:features>
'''
I would consider this bug closed/works as expected.

**Comment by mdosch** [comment]
talk.google.com is history, therefore I'll close this issue.
